nimble c --app:console ^
    --out:..\dist/pocketsocket-cli.exe ^
    --threads:on ^
    --tlsEmulation:off ^
    -d:lto ^
    --mm:arc ^
    -d:useMalloc ^
    -d:release ^
    --opt:speed ^
    -d:strip ^
    --passL:-static src/pocketsocket.nim
